<?php

namespace Database\Seeders;

use App\Models\Pengajuan;
use App\Enums\PengajuanStatus;
use Illuminate\Database\Seeder;

class PengajuanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();
        Pengajuan::insert([
                [
                    'nama' => "Syahla Salsabila",
                    'nim' => '11111',
                    'jurusan' => 'Teknik Komputer dan Informatika',
                    'prodi' => 'D3-Teknik Informatika',
                    'ormawa' => 'HIMAKOM',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '6289',
                    'email' => 'test10@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Tita Erlina",
                    'nim' => '22222',
                    'jurusan' => 'Bahasa Inggris',
                    'prodi' => 'D3-Bahasa Inggris',
                    'ormawa' => 'HIMARIS',
                    'periode' => '2024-2025',
                    'ketua_ormawa' => 'HMJ',
                    'telp' => '6289',
                    'email' => 'test2@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Rina Nana",
                    'nim' => '33333',
                    'jurusan' => 'Teknik Mesin',
                    'prodi' => 'D3-Teknik Mesin',
                    'ormawa' => 'HMJTM',
                    'periode' => '2024-2025',
                    'ketua_ormawa' => 'test',
                    'telp' => '6289',
                    'email' => 'test@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                // Data tambahan lainnya
                [
                    'nama' => "Ali Imron",
                    'nim' => '44444',
                    'jurusan' => 'Teknik Energi',
                    'prodi' => 'D4-Konservasi Energi',
                    'ormawa' => 'HMTE',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '6281234',
                    'email' => 'ali@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Budi Santoso",
                    'nim' => '111222',
                    'jurusan' => 'Teknik Elektronika',
                    'prodi' => 'D4-Teknik Elektronika',
                    'ormawa' => 'HME',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '628111222',
                    'email' => 'budi@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Eka Saputra",
                    'nim' => '222333',
                    'jurusan' => 'Administrasi Bisnis',
                    'prodi' => 'D3-Administrasi Bisnis',
                    'ormawa' => 'HMAB',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '628222333',
                    'email' => 'eka@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Fitriani Adinda",
                    'nim' => '333444',
                    'jurusan' => 'Desain Komunikasi Visual',
                    'prodi' => 'D4-Desain Komunikasi Visual',
                    'ormawa' => 'HMV',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '628333444',
                    'email' => 'fitri@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Galih Pratama",
                    'nim' => '444555',
                    'jurusan' => 'Teknik Industri',
                    'prodi' => 'D3-Teknik Industri',
                    'ormawa' => 'HMTI',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '628444555',
                    'email' => 'galih@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Hani Rizky",
                    'nim' => '555666',
                    'jurusan' => 'Teknik Komputer dan Informatika',
                    'prodi' => 'D4-Teknik Informatika',
                    'ormawa' => 'HMITI',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '628555666',
                    'email' => 'hani@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Indra Maulana",
                    'nim' => '666777',
                    'jurusan' => 'Teknik Kimia',
                    'prodi' => 'D4-Teknologi Kimia',
                    'ormawa' => 'HMTK',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '628666777',
                    'email' => 'indra@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Johan Aditya",
                    'nim' => '777888',
                    'jurusan' => 'Manajemen Pemasaran',
                    'prodi' => 'D4-Manajemen Pemasaran',
                    'ormawa' => 'HMM',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '628777888',
                    'email' => 'johan@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ],
                [
                    'nama' => "Kiki Putri",
                    'nim' => '888999',
                    'jurusan' => 'Teknik Sipil',
                    'prodi' => 'D3-Konstruksi Bangunan',
                    'ormawa' => 'HMS',
                    'ketua_ormawa' => 'HMJ',
                    'periode' => '2024-2025',
                    'telp' => '628888999',
                    'email' => 'kiki@gmail.com',
                    'created_at' => $now,
                    'updated_at' => $now,
                    'status' => PengajuanStatus::Diterima->value,
                ]

            
        ]);
    }
}
